# Site settings
title: Notes on programming.
email: iliasashaikh@gmail.com
description: >
  These are mostly notes to myself. Things that I have learnt, mistakes I have made, and projects that I am working on.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "www.trycatchthat.com" # the base hostname & protocol for your site
twitter_username: iliasshaikh
github_username:  iliasashaikh

# Build settings
markdown: kramdown
